title: Hope Community Church
author: hope-community
email: hopechurchnorman@gmail.com
description: >
  A website for Hope Community Church in Norman, OK
github_username:  hopechurchnorman
plugins:
  - jekyll-seo-tag
sass:
  style: compact
